blog/urls.py
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse
from django.contrib.auth import views as auth_views
from django.conf.urls.defaults import patterns, include, url
from django.contrib.auth.decorators import login_required, permission_required


from blog import views
from blog.models import Post, Comment

urlpatterns = patterns('',
	url(r'^$', views.PostsList.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^add/$', permission_required('blog:add_post', login_url='/blog/login/') (views.PostCreate.as_view()), name='post_add'),

	url(r'^comment/add/$', views.CommentAdd.as_view(), name='comment_add'),

	url(r'^login/$', views.LoginForm, name='login'),
	url(r'^logout/$', views.Logout, name='logout'),
	url(r'^register/$', views.NewUser, name='register'),	
)

trilantest/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'trilantest.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^admin/', include(admin.site.urls)),
)

blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

class Post(models.Model):
	title = models.CharField(max_length=200)
	content = models.TextField()
	pub_date = models.DateTimeField()

	class Meta:
		ordering = ["-pub_date"]

	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:index')

class Comment(models.Model):
	post = models.ForeignKey(Post)
	content = models.TextField()
	user = models.ForeignKey(User)
	pub_date = models.DateTimeField(default=timezone.now())

	class Meta:
		ordering = ["pub_date"]

	def get_absolute_url(self):
		return reverse('blog:detail', args=(self.post.pk,))

	def __unicode__(self):
		return self.content

blog/forms.py
from django import forms

class ContactForm(forms.Form):
	name = forms.CharField()
	message = forms.CharField(widget=forms.Textarea)

	def send_email():
		pass

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login
from django import forms
from django.forms.util import ErrorList
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import Group

from blog.models import Post, Comment
from blog.forms import ContactForm

from django.contrib.auth.views import login as login_view, logout

import json


class PostsList(generic.ListView):
	model = Post
	context_object_name = 'latest_posts_list'
	paginate_by = 3

class DetailView(generic.DetailView):
	model = Post
	template_name = 'blog/detail.html'

class PostCreate(generic.edit.CreateView):
	model = Post
	fields = ['title', 'content']

	def form_valid(self, form):
		form.instance.pub_date = timezone.now()
		response = super(generic.edit.CreateView, self).form_valid(form)
		return response

class CommentAdd(generic.edit.CreateView):
	model = Comment
	fields = ['content', 'post']

	def form_valid(self, form):
		form.instance.pub_date = timezone.now()
		form.instance.user = self.request.user
		response = super(generic.edit.CreateView, self).form_valid(form)
		return response

def LoginForm(request):
	if not request.user.is_authenticated():
		return login_view(request, template_name='blog/login.html', extra_context = 
				{
					'next': '/blog/'
				}
			)
	else:
		return HttpResponseRedirect( reverse('blog:index') )

def NewUser(request):
	user_creation_form = UserCreationForm(data = request.POST or None)
	if user_creation_form.is_valid():

		new_user = user_creation_form.save()
		commentators = Group.objects.get(name='commentators')
		commentators.user_set.add(new_user)
		
		new_user = authenticate(username=user_creation_form.cleaned_data['username'], 
								password=user_creation_form.cleaned_data['password1'])
		auth_login(request, new_user)

		return HttpResponseRedirect( reverse('blog:index') )
	else:
		return render(request, 'blog/registration.html', {'form': user_creation_form})

def Logout(request):
	return logout(request, next_page=reverse('blog:index'))

blog/templates/blog/detail.html
{% extends "blog/post_list.html" %}

{% load staticfiles %}

{% block main_content %}

	<div class="row">
		<div class="col-md-8 blog-main">
			<div class="blog-post"></div>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-8 blog-main">
				<div class="blog-post">
					<h2 class="blog-post-title">{{ post.title }}</h2>
					<p class="blog-post-meta">{{ post.pub_date }}</p>
					<p>{{ post.content }}</p>
				</div>
			</div>			
		</div>
		
		{% if post.comment_set.count > 0 %}
			<div class="row">
				<div class="col-md-8 blog-main">
					<h4>Комментарии:</h4>
				</div>			
			</div>
			{% for comment in post.comment_set.all %}
				<div class="row">
					<div class="col-md-8 blog-comment">
						<p>{{ comment.content }} <br> 
						
						<span class="comment-meta">
							<span class="comment-author">{{ comment.user.username }}</span>
							<span class="comment-date">{{ comment.pub_date|date:"d.m.Y h:m" }}</span>
						</span>
					</div>			
				</div>
			{% endfor %}
		{% endif %}
		
		{% if perms.blog.add_comment %}
			<div class="row">
				<div class="col-md-8 blog-comment">
					<form action="{% url 'blog:comment_add' %}" method="POST" role="form">
						<fieldset>
							<legend>Добавить комментарий:</legend>
							{% csrf_token %}
							<div class="form-group">
								<!-- <label class="control-label" for="content">Пост: </label> -->
								<textarea type="text" rows="3" id="content" name="content" placeholder="Контент" required="" class="form-control"></textarea>
							</div>

							<input type="hidden" name="post" value="{{ post.id }}">
							<input class="btn btn-default" type="submit">
						</fieldset>
					</form>
				</div>
			</div>
		{% else %}
			<div class="row">
				<div class="col-md-8 blog-comment">
					<a href="{% url 'blog:login' %}">Войдите</a> или <a href="{% url 'blog:register' %}">зарегистрируйтесь</a> чтобы оставлять комментарии
					<br><br>
				</div>
			</div>
		{% endif %}
	</div>
{% endblock %}

blog/templates/blog/login.html
{% extends "blog/post_list.html" %}

{% load staticfiles %}

{% block main_content %}
	
<div class="container">
	<div class="row">

		<div class="col-md-8 blog-main">
			{% if form.errors %}
				<br>
				<p>Your username and password didn't match. Please try again.</p>
			{% endif %}
		</div>

		<div class="col-md-8 blog-main">
			<form action="{% url 'blog:login' %}" method="POST" role="form" class="form-horizontal">
				<fieldset>
					<legend>Вход:</legend>
					{% csrf_token %}
						<div class="form-group">
							<label for="username" class="col-sm-4 control-label">Username:</label>
							<div class="col-sm-6">
								<input class="form-control" id="username" placeholder="Username" name="username" 
								value="{{ form.username.value|default:'' }}">
							</div>
						</div>

						<div class="form-group">
							<label for="inputPassword" class="col-sm-4 control-label">Password:</label>
							<div class="col-sm-6">
								<input type="password" class="form-control" id="inputPassword" name="password" placeholder="Password"
								value="{{ form.password.value|default:'' }}">
							</div>
						</div>

						<input type="hidden" name="next" value="{{ next }}" />
						<input class="btn btn-default" type="submit" value="Войти">
				</fieldset>
			</form>
		</div>

	</div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Post list</title>

	<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
</head>
<body>
	
	<div class="blog-masthead">
		<div class="container">
			<nav class="blog-nav">
			<div class="row">
				<div class="col-md-4 col-md-offset-8">
					{% if not user.is_authenticated %}
						<a class="blog-nav-item" href="{% url 'blog:login' %}">Login</a>
					{% else %}
						<span class="blog-nav-item active">{{ user.username }}</span>
						<a class="blog-nav-item" href="{% url 'blog:logout' %}">Logout</a>
					{% endif %}			
				</div>
			</div>
			</nav>
		</div>
	</div>

	{% block main_content %}
	<div class="container">
			
			<div class="row">
				<div class="col-md-8 blog-main">
					<div class="blog-post">
						{% if perms.blog.add_post %}
							{% block create_post_form %}
								<form action="{% url 'blog:post_add' %}" method="POST" role="form">
									<fieldset>
										<legend>Создать новый пост</legend>
										{% csrf_token %} 
										<div class="form-group">
											<label class="control-label" for="title">Заголовок: </label>
											<input type="text" id="title" name="title" placeholder="Заголовок" required="" class="form-control">
										</div>
										
										<div class="form-group">
											<label class="control-label" for="content">Пост: </label>
											<textarea type="text" rows="3" id="content" name="content" placeholder="Контент" required="" class="form-control"></textarea>
										</div>
															
										<input class="btn btn-default" type="submit">
									</fieldset>
								</form>
							
								<script src="{% static 'blog/js/jquery.form.min.js' %}"></script>
								<script src="{% static 'blog/js/myscript.js' %}"></script>
							{% endblock %}
						{% endif %}
					</div>
				</div>
			</div>
		
		{% if latest_posts_list %}

			{% for post in latest_posts_list %}
				<div class="row">
					<div class="col-md-8 blog-main">
						<div class="blog-post">
							<h2 class="blog-post-title"><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h2>
							<p class="blog-post-meta">{{ post.pub_date|date:"d.m.Y h:m" }}</p>
							<p>{{ post.content }}</p>
						</div>
					</div>			
				</div>
			{% endfor %}
			
			<div class="pagination">
				<span class="step-links">
				{% if page_obj.has_previous %}
					<a href="?page={{ page_obj.previous_page_number }}">previous</a>
				{% endif %}
					<span class="current">
					Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
					</span>
				{% if page_obj.has_next %}
					<a href="?page={{ page_obj.next_page_number }}">next</a>
				{% endif %}
				</span>
			</div>

		{% else %}
			<p>No posts are available.</p>
		{% endif %}

	</div>
	{% endblock %}

<script src="{% static 'blog/js/jquery-2.1.1.js' %}"></script>
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
</body>
</html>

blog/templates/blog/registration.html
{% extends "blog/post_list.html" %}

{% load staticfiles %}

{% block main_content %}
	<div class="container">
		<div class="row">

			<div class="col-md-8 blog-main">
				{% if form.errors %}
					<br>
					<p>{{ form.errors }}</p>
				{% endif %}
			</div>

			<div class="col-md-8 blog-main">
				<form action="{% url 'blog:register' %}" method="POST" role="form" class="form-horizontal">
					<fieldset>
						<legend>Регистрация:</legend>
						{% csrf_token %}
							<div class="form-group">
								<label for="username" class="col-sm-4 control-label">Username:</label>
								<div class="col-sm-6">
									<input class="form-control" id="username" placeholder="Username" name="username" 
									value="{{ form.username.value|default:'' }}">
								</div>
							</div>

							<div class="form-group">
								<label for="inputPassword1" class="col-sm-4 control-label">Password:</label>
								<div class="col-sm-6">
									<input type="password" class="form-control" id="inputPassword1" name="password1" placeholder="Password"
									value="{{ form.password1.value|default:'' }}">
								</div>
							</div>

							<div class="form-group">
								<label for="inputPassword2" class="col-sm-4 control-label">Password once again:</label>
								<div class="col-sm-6">
									<input type="password" class="form-control" id="inputPassword2" name="password2" placeholder="Password"
									value="{{ form.password2.value|default:'' }}">
								</div>
							</div>

							<input type="hidden" name="next" value="{{ form.next.value }}" />
							<input class="btn btn-default" type="submit" value="Войти">
					</fieldset>
				</form>
			</div>

		</div>
	</div>
{% endblock %}